name: app_my_pham
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

#------packages---#
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  iconsax_flutter: ^1.0.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  carousel_slider: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/categories/
    - assets/logos/
    - assets/images/banners/
    - assets/images/onboarding/
    - assets/images/verify/
    - assets/images/products/
    - assets/images/products/perfume/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800